on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest-stable
      - uses: xavierLowmiller/xcodegen-action@1.2.4
        with:
          spec: project.yml
          quiet: true
      - name: Generate Xcode project
        run: xcodegen generate


      - name: Build
        run: |
          xcodebuild \
          -project ZMKBatteryUtil.xcodeproj \
          -scheme ZMKBatteryUtil \
          -configuration Release \
          -derivedDataPath build/DerivedData \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          build


      - name: Self Sign app
        if: ${{ secrets.SIGN_CERT_B64}}  != '' && ${{ secrets.CERT_PASS!= '' }}
        env:
          SIGN_CERT_B64: ${{ secrets.SIGN_CERT_B64 }}
          CERT_PASS : ${{ secrets.CERT_PASS }}
        run: |
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
            CERTIFICATE_P12_PATH=$RUNNER_TEMP/certificate.p12
            APP_PATH="build/DerivedData/Build/Products/Release/ZMKBatteryUtil.app"

            echo -n "$SIGN_CERT_B64" | base64 --decode -o $CERTIFICATE_P12_PATH

            security create-keychain -p "$CERT_PASS" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "$CERT_PASS" $KEYCHAIN_PATH

            security import $CERTIFICATE_P12_PATH -P "$CERT_PASS" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          
            IDENTITY=$(security find-identity -v -p codesigning $KEYCHAIN_PATH | head -n 1 | grep -o '".*"' | sed 's/"//g')
            echo "Signing with identity: $IDENTITY"

            codesign --force --deep --sign "$IDENTITY" --keychain $KEYCHAIN_PATH "$APP_PATH"
            security delete-keychain $KEYCHAIN_PATH
            rm -f $CERTIFICATE_P12_PATH

      - name: Install create-dmg
        run: brew install create-dmg
      - name: Create DMG
        run: |
          APP_DIR="build/DerivedData/Build/Products/Release"
          APP_NAME="ZMKBatteryUtil.app"         
          VOL_NAME="ZMKBatteryUtil"            

          rm -rf dist dmgroot
          mkdir -p dist dmgroot
          cp -R "$APP_DIR/$APP_NAME" dmgroot/

          create-dmg --volname "ZMKBatteryUtil" --window-size 600 400 --app-drop-link 450 200 dist/ZMKBatteryUtil.dmg "dmgroot"


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with: 
          tag_name: ZMKBatteryUtil-${{github.sha}}
          release_name: ZMKBatteryUtil-Release-${{github.sha}}
          body: |
            Release of ZMKBatteryUtil
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DMG 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}  
          asset_path: dist/ZMKBatteryUtil.dmg
          asset_name: ZMKBatteryUtil.dmg
          asset_content_type: applicationk/x-apple-diskimage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}









