on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v2
        with: 
          swift-version: '6.1.0'
      - name: Cache Mint packages
        id: cache-mint
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOME }}/.mint
            ${{ env.HOME }}/.mint/bin
          key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-



      - name: Mint cache test
        run : echo "cache-hit = ${{steps.cache-mint.outputs.cache-hit}}"
      - name: Install Mint
        run: brew install mint

      - name: Add Mint Packages to Path
        run: echo "$HOME/.mint/bin" >> $GITHUB_PATH
      - name: Bootstrap via Mint
        run: mint bootstrap
      - name: Build Swift Package
        run: swift build -c release
      - name: Swift version 
        run: swift --version
      - name: Bundle Swift Package
        run: swift-bundler bundle -c release -o . -u
